[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
lib_deps = 
    GxEPD2
    ESP32Async/ESPAsyncWebServer @ 3.11.1
    ESP32Async/AsyncTCP @ 3.4.10
    ArduinoJson
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1 -Ilib

board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB
upload_protocol = esptool
; Uncomment and set IP for OTA upload:
; upload_protocol = espota
; upload_port = 192.168.1.114

[env:m5cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.psram = enable
board_build.psram_mode = opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
upload_speed = 1500000
upload_protocol = esptool
lib_deps = 
    M5Cardputer=https://github.com/m5stack/M5Cardputer
    ESP32Async/ESPAsyncWebServer @ 3.11.1
    ESP32Async/AsyncTCP @ 3.4.10
    ArduinoJson
build_flags = 
    -DUSE_CARDPUTER
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=5
    -Ilib
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
